export const GH_API = "https://api.github.com";
export const MAX_CONCURRENCY = 8;
export const MAX_RETRIES = 4;
export const RETRY_BASE_MS = 400;
export const MAX_TEXT_BLOB_BYTES = 5 * 1024 * 1024;
export const AVERAGE_REQUEST_LATENCY_MS = 350;
export const OUT_DIR = "out";
export const PROGRESS_UPDATE_INTERVAL_MS = 150;

export const TEXT_EXTENSIONS = new Set(
  [
    ".txt",
    ".md",
    ".markdown",
    ".mdx",
    ".gitignore",
    ".gitattributes",
    ".yml",
    ".yaml",
    ".json",
    ".jsonc",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".css",
    ".scss",
    ".less",
    ".html",
    ".htm",
    ".xml",
    ".svg",
    ".py",
    ".rb",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".c",
    ".cpp",
    ".h",
    ".hpp",
    ".sh",
    ".bash",
    ".zsh",
    ".dockerfile",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".properties",
    ".env",
    ".sql",
    ".r",
    ".lua",
    ".pl",
    ".scala",
    ".hs",
  ].map((extension) => extension.toLowerCase())
);

export const SKIP_EXTENSIONS = new Set(
  [
    // Raster/vector images
    ".apng",
    ".avif",
    ".bmp",
    ".dcm",
    ".gif",
    ".heic",
    ".heif",
    ".ico",
    ".icns",
    ".jpeg",
    ".jpg",
    ".jxl",
    ".png",
    ".psd",
    ".svgz",
    ".tif",
    ".tiff",
    ".webp",
    // Audio formats
    ".aac",
    ".aif",
    ".aiff",
    ".amr",
    ".flac",
    ".m4a",
    ".mid",
    ".midi",
    ".mp3",
    ".ogg",
    ".wav",
    ".wma",
    // Video formats
    ".3gp",
    ".3g2",
    ".avi",
    ".flv",
    ".m4v",
    ".mkv",
    ".mov",
    ".mp4",
    ".m2ts",
    ".mpeg",
    ".mpg",
    ".mts",
    ".ogv",
    ".webm",
    ".wmv",
    // Fonts
    ".eot",
    ".otf",
    ".ttf",
    ".woff",
    ".woff2",
    // Office & design documents
    ".ai",
    ".doc",
    ".docx",
    ".eps",
    ".indd",
    ".odp",
    ".ods",
    ".odt",
    ".pdf",
    ".ppt",
    ".pptx",
    ".vsd",
    ".vsdx",
    ".xls",
    ".xlsx",
    // Archives and disk images
    ".7z",
    ".apk",
    ".cab",
    ".deb",
    ".dmg",
    ".ear",
    ".gz",
    ".gzip",
    ".img",
    ".iso",
    ".jar",
    ".lz",
    ".lz4",
    ".lzma",
    ".msi",
    ".pkg",
    ".rar",
    ".rpm",
    ".sit",
    ".sitx",
    ".tar",
    ".tbz2",
    ".tgz",
    ".war",
    ".xz",
    ".z",
    ".zip",
    ".zst",
    // Compiled binaries & bytecode
    ".a",
    ".app",
    ".bin",
    ".class",
    ".dll",
    ".dylib",
    ".exe",
    ".lib",
    ".o",
    ".obj",
    ".pyc",
    ".pyo",
    ".so",
    ".wasm",
    // Databases and opaque data
    ".db",
    ".db3",
    ".realm",
    ".sqlite",
    ".sqlite3",
    // Lock and generated state files
    ".lock",
    ".lock.json",
    ".lockfile",
  ].map((extension) => extension.toLowerCase())
);
